### ISSUE TITLE
Question regarding the used model in tutorial?

### ISSUE THREAD

**Issue by debparth** [mtchibozo/FCN2s#1]
The model which you're using in Tutorial for fine tuning with custom dataset. The pre-trained model which you fine tuned from coco dataset on the Table Dataset. Can I use it to train on Custom Table Dataset which is only having 2 Category (Table and Column)? or should I fine tuned the model like you did on my dataset?

**Comment by mtchibozo** [comment]
This code is for fine-tuning. To fully train you would need to manually select the layers you want to "un-freeze" in the architecture. For your use case I recommend following the same approach detailed in this code to fine-tune on your Custom Dataset. The code gives enough flexibility to modify the types of output classes to only Table and Column. I have done this in the past and it gave good results.
